lsi: false
safe: true
source: ezm2ng's page
theme: jekyll-theme-slate
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#   math_engine: mathjax
#   syntax_highlighter: rouge
google_analytics: G-1B3Y7VTC45